# Generated by Django 3.0.3 on 2020-02-09 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('almajlis', '0002_comment_session'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='title',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
