# Generated by Django 3.0.3 on 2020-02-10 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('almajlis', '0003_session_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
