# Generated by Django 3.0.3 on 2020-02-10 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('almajlis', '0004_candidate_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='citizen',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
